### ISSUE TITLE
Move examples

### ISSUE THREAD

**Issue by setrar** [OlivierNicole/haskell-chess#3]
Hi,

What would be some move examples? 
I am trying to figure it out through code but a quick help will be appreciated. 
Cheers

**Comment by OlivierNicole** [comment]
Hi @setrar,

An example of move would be the string `e2e4`, which will get parsed into the value `Move (4,1) (4,3)`.

**Comment by setrar** [comment]
Hi @OlivierNicole 

I took some time, about a week, to figure it out. 

I was able to find the answer [:point_right: Move Examples](https://github.com/setrar/haskell-chess/tree/main#move-examples)

While going through the code, I did a bit of refactoring (mainly getting rid of `Input.hs`) and converted the project to `cabal`

I was mostly interested in your `alpha-beta pruning` implementation.

Thanks

**Comment by OlivierNicole** [comment]
Hi @setrar,

Glad my student project was of interest to you. The alpha-beta algorithm is largely drawn from John Hughes's inspiring paper “Why functional programming matters”. It was what prompted me to write this program in the first place. 

Le 13 novembre 2021 17:39:23 GMT+01:00, setrar ***@***.***> a écrit :

**Comment by setrar** [comment]
> [Why_Functional_Programming_Matters - John Hughes, Institutionen för Datavetenskap,](https://www.researchgate.net/publication/2452204_Why_Functional_Programming_Matters)

I got the book reference. 

Your CLI student project helped me rethinking about a side project [Fanorona](https://github.com/gasy-africa/fanorona/tree/main/java/docs) by [Dr Epstein](https://www.ics.uci.edu/~eppstein/) that I have been trying to reverse engineer (from Java) for quite a while, from Imperative to Functional.

Thanks
